services:
  # Backend API
  - type: web
    name: proxy-assessment-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements-render.txt
      mkdir -p geoip
      curl -L "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb" -o geoip/GeoLite2-City.mmdb
    startCommand: |
      cd backend
      python proxy_tester.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://proxy-assessment-tool.vercel.app
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    autoDeploy: false

  # Redis Instance
  - type: redis
    name: proxy-assessment-redis
    region: oregon
    plan: free
    ipAllowList: []

# Database (optional - for persistence)
databases:
  - name: proxy-assessment-db
    plan: free
    databaseName: proxydb
    user: proxyuser