name: No Static Content Guard

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  check-static:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for forbidden static content
      run: |
        echo "🔍 Checking for static/mock content in production files..."
        
        FORBIDDEN_PATTERNS="mock|fixture|demo|placeholder|TODO|FIXME|staticData|stub|lorem"
        PROD_FILES=$(find ./extension/src -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | grep -v ".test." | grep -v ".spec." | grep -v "__tests__")
        
        VIOLATIONS=0
        echo "Files with static content:"
        echo "========================="
        
        for file in $PROD_FILES; do
          # Skip test files and Field component (placeholder is OK for form fields)
          if [[ "$file" == *"Field.tsx"* ]] || [[ "$file" == *"/tests/"* ]]; then
            continue
          fi
          
          # Check for real static data, not UI placeholders
          if grep -E "(mock[A-Z]|fixture[A-Z]|staticData|TODO|FIXME|placeholder candidates)" "$file" > /dev/null 2>&1; then
            echo "❌ STATIC CONTENT IN: $file"
            grep -n -E "(mock[A-Z]|fixture[A-Z]|staticData|TODO|FIXME|placeholder candidates)" "$file" | head -5
            VIOLATIONS=$((VIOLATIONS + 1))
          fi
        done
        
        if [ $VIOLATIONS -gt 0 ]; then
          echo ""
          echo "⛔ Build failed: $VIOLATIONS files contain forbidden static content"
          echo "Replace with real data fetches or remove the static content."
          exit 1
        else
          echo "✅ No forbidden static content found in production files"
        fi
    
    - name: Verify buttons are wired
      run: |
        echo "🔍 Verifying UI buttons have real handlers..."
        
        # Check popup buttons
        if ! grep -q "openDashboard" ./extension/dist/js/popup.js 2>/dev/null; then
          echo "❌ Dashboard button not wired in popup"
          exit 1
        fi
        
        if ! grep -q "openSettings" ./extension/dist/js/popup.js 2>/dev/null; then
          echo "❌ Settings button not wired in popup"
          exit 1
        fi
        
        # Check background handlers
        if ! grep -q "openDashboard.*chrome.tabs.create" ./extension/dist/js/background.js 2>/dev/null; then
          echo "❌ Dashboard handler missing in background"
          exit 1
        fi
        
        echo "✅ All buttons properly wired"